Update markdown documents
terraform-ibm-modules/terraform-ibm-powervs-sap pull request #595
Opened 2024-01-17 16:40 UTC by vburckhardt

**LLM-Assisted Editing Enhancement**

To make the most of your modifications or further developments, it's advisable to use the specific branch from which this Pull Request (PR) originates. This will ensure you have a solid and up-to-date foundation for your tweaks and enhancements.

_Using [Markdown LLM Corrector](https://github.com/vburckhardt/markdown-llm-corrector)._

2024-01-23 11:38 UTC, surajsbharadwaj commented on tests/README.md
> +For information about how to create and run tests, see [Validation Tests](https://terraform-ibm-modules.github.io/documentation/#/tests) in the project documentation.
```Suggestions
new
```

2024-01-23 16:33 UTC, SirSpidey requested changes
@vburckhardt I think the capitalization changes do more harm than good. I suggest disabling those changes if they can't be set to sentence capitalization.

2024-01-23 16:33 UTC, SirSpidey commented on README.md
> +### IBM Catalog Solutions requiring pre-requisite Schematics Workspace ID of [Power Virtual Server with vpc landing zone](https://cloud.ibm.com/catalog/architecture/deploy-arch-ibm-pvs-inf-2dd486c7-b
```suggestion
### IBM catalog solutions that require a Schematics workspace ID of [Power Virtual Server with VPC landing zone](https://cloud.ibm.com/catalog/architecture/deploy-arch-ibm-pvs-inf-2dd486c7-b317-4aaa-907b-42671485ad96-global)
```

2024-01-23 16:33 UTC, SirSpidey commented on README.md
> +    - Creates and configures **one HANA instance, zero to several NetWeaver instances, and one optional ShareFS** with **RHEL or SLES OS** distribution. Creates a new private subnet for SAP communica
```suggestion
    - Creates and configures **one HANA instance, zero to several NetWeaver instances, and one optional ShareFS** with **RHEL or SLES OS** distribution. Creates a private subnet for SAP communication for the entire landscape and attaches it to cloud connections (in non-PER DC).
```

2024-01-23 16:33 UTC, SirSpidey commented on README.md
> +    - Creates and configures **one HANA instance, one NetWeaver instance, and one optional ShareFS** with **RHEL** OS distribution. Creates a new private subnet for SAP communication for the entire l
```suggestion
    - Creates and configures **one HANA instance, one NetWeaver instance, and one optional ShareFS** with **RHEL** OS distribution. Creates a private subnet for SAP communication for the entire landscape and attaches it to cloud connections (in non-PER DC).
```

2024-01-23 16:33 UTC, SirSpidey commented on README.md
> +### Solutions Independent of IBM Cloud Pre-requisite Schematics Workspace ID:
```suggestion
### Solutions independent of IBM Cloud prerequisite Schematics workspace ID:
```

2024-01-23 16:33 UTC, SirSpidey commented on README.md
> +1. [PowerVS SAP Ready Variation](https://github.com/terraform-ibm-modules/terraform-ibm-powervs-sap/tree/main/solutions/sap-ready-to-go)
```suggestion
1. [PowerVS SAP Ready variation](https://github.com/terraform-ibm-modules/terraform-ibm-powervs-sap/tree/main/solutions/sap-ready-to-go)
```

2024-01-23 16:33 UTC, SirSpidey commented on README.md
> +   - Creates and configures **one HANA instance, zero to several NetWeaver instances and one optional ShareFS** with **RHEL or SLES OS** distribution. Creates a new private subnet for SAP communicati
```suggestion
   - Creates and configures **one HANA instance, zero to several NetWeaver instances and one optional ShareFS** with **RHEL or SLES OS** distribution. Creates a private subnet for SAP communication for the entire landscape, and attaches it to cloud connections (in non-PER DC).
```

2024-01-23 16:33 UTC, SirSpidey commented on README.md
> +    - Creates and configures **one HANA instance, zero to several NetWeaver instances, and one optional ShareFS** with **RHEL or SLES OS** distribution. Creates a new private subnet for SAP communica
```suggestion
    - Creates and configures **one HANA instance, zero to several NetWeaver instances, and one optional ShareFS** with **RHEL or SLES OS** distribution. Creates a private subnet for SAP communication for the entire landscape, and attaches it to cloud connections (in non-PER DC).
```

2024-01-23 16:33 UTC, SirSpidey commented on README.md
> +## Reference Architectures
```suggestion
## Reference architectures
```

2024-01-23 16:33 UTC, SirSpidey commented on README.md
> +To set up your local development environment, see [Local Development Setup](https://terraform-ibm-modules.github.io/documentation/#/local-dev-setup) in the project documentation.
```suggestion
To set up your local development environment, see [Local development setup](https://terraform-ibm-modules.github.io/documentation/#/local-dev-setup) in the project documentation.
```

2024-01-23 16:33 UTC, SirSpidey commented on modules/pi-sap-system-type1/README.md
> +- Creates a new private subnet for SAP communication for the entire landscape and attaches it to cloud connections (in Non-PER DC).
```suggestion
- Creates a private subnet for SAP communication for the entire landscape, and attaches it to cloud connections (in non-PER DC).
```

2024-01-23 16:33 UTC, SirSpidey commented on reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
>  related_links:
use the original capitalization for this whole section. Especially the property names.

2024-01-23 16:33 UTC, SirSpidey commented on reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
> +## Architecture Diagram
```suggestion
## Architecture diagram
```

2024-01-23 16:33 UTC, SirSpidey commented on reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
> +![Architecture Diagram for SAP on Power Virtual Server for SAP HANA - Variation SAP Ready PowerVS](deploy-arch-ibm-pvs-sap-ready-to-go.svg "Architecture Diagram"){: caption="Figure 1. PowerVS Instanc
```suggestion
![Architecture diagram for SAP on Power Virtual Server for SAP HANA - variation SAP Ready PowerVS](deploy-arch-ibm-pvs-sap-ready-to-go.svg "Architecture diagram"){: caption="Figure 1. PowerVS instances prepared to Run SAP in PowerVS Workspace" caption-side="bottom"}{: external download="deploy-arch-ibm-pvs-sap-ready-to-go.svg"}
```

2024-01-23 16:33 UTC, SirSpidey commented on reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
> +## Design Requirements
```suggestion
## Design requirements
```

2024-01-23 16:33 UTC, SirSpidey commented on reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
> +![Design Requirements for 'Power Virtual Server for SAP HANA' - Variation 'SAP Ready PowerVS'](heat-map-deploy-arch-ibm-pvs-sap-ready-to-go.svg "Design Requirements"){: caption="Figure 2. Scope of th
```suggestion
![Design requirements for 'Power Virtual Server for SAP HANA' - variation 'SAP Ready PowerVS'](heat-map-deploy-arch-ibm-pvs-sap-ready-to-go.svg "Design requirements"){: caption="Figure 2. Scope of the solution requirements" caption-side="bottom"}
```

2024-01-23 16:33 UTC, SirSpidey commented on reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
> +## Next Steps
```suggestion
## Next steps
```

2024-01-23 16:33 UTC, SirSpidey commented on reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
>  related_links:
same as other Ref arch comment. Don't change this capitalization.

2024-01-23 16:33 UTC, SirSpidey commented on reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
> +## Architecture Diagram
```suggestion
## Architecture diagram
```

2024-01-23 16:33 UTC, SirSpidey commented on reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
> +## Design Requirements
```suggestion
## Design requirements
```

2024-01-23 16:33 UTC, SirSpidey commented on reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
> +![Design Requirements for "Power Virtual Server for SAP HANA" - Variation "SAP S/4HANA or BW/4HANA"](heat-map-deploy-arch-ibm-pvs-sap-s4hana-bw4hana.svg "Design Requirements"){: caption="Figure 2. Sc
```suggestion
![Design requirements for "Power Virtual Server for SAP HANA" - variation "SAP S/4HANA or BW/4HANA"](heat-map-deploy-arch-ibm-pvs-sap-s4hana-bw4hana.svg "Design requirements"){: caption="Figure 2. Scope of the Solution requirements" caption-side="bottom"}
```

2024-01-23 16:33 UTC, SirSpidey commented on solutions/e2e/README.md
> +# End-to-End Solution: Power Virtual Server with VPC Landing Zone Including Power Virtual Server for SAP HANA Instances
```suggestion
# End-to-end solution: Power Virtual Server with VPC landing zone including Power Virtual Server for SAP HANA instances
```

2024-01-23 16:33 UTC, SirSpidey commented on solutions/e2e/README.md
> +        - Provisions three VPCs with one VSI in each VPC - one management (jump/bastion) VSI, one inet-svs VSI configured as a squid proxy server, and one private-svs VSI (configured as NFS, NTP, DNS
```suggestion
        - Provisions three VPCs with one VSI in each VPC: one management (jump/bastion) VSI, one inet-svs VSI configured as a squid proxy server, and one private-svs VSI (configured as NFS, NTP, DNS server) using [this preset](https://github.com/terraform-ibm-modules/terraform-ibm-powervs-infrastructure/blob/main/modules/powervs-vpc-landing-zone/presets/3vpc.preset.json.tftpl).
```

2024-01-23 16:33 UTC, SirSpidey commented on solutions/e2e/README.md
> +    - Creates a new private subnet for SAP communication for the entire landscape and attaches it to cloud connections (in Non PER DC).
```suggestion
    - Creates a new private subnet for SAP communication for the entire landscape and attaches it to cloud connections (in non-PER DC).
```

2024-01-23 16:33 UTC, SirSpidey commented on solutions/e2e/README.md
> +- Post-instance provisioning, Ansible Galaxy collection roles from [IBM](https://galaxy.ansible.com/ui/repo/published/ibm/power_linux_sap/) are executed: `power_linux_sap`.
not sure whether this change is correct

2024-01-23 16:33 UTC, SirSpidey commented on solutions/ibm-catalog/sap-ready-to-go/README.md
> +- Post-instance provisioning, Ansible Galaxy collection roles from [IBM](https://galaxy.ansible.com/ui/repo/published/ibm/power_linux_sap/) are executed: `power_linux_sap`.
same as previous. not sure if this is correct.

2024-01-23 16:33 UTC, SirSpidey commented on solutions/ibm-catalog/sap-s4hana-bw4hana/README.md
> +## Before You Begin
```suggestion
## Before you begin
```

2024-01-23 16:33 UTC, SirSpidey commented on solutions/ibm-catalog/sap-s4hana-bw4hana/README.md
> +### 1. IBM Cloud Object Storage Service Credentials
```suggestion
### 1. IBM Cloud Object Storage service credentials
```

2024-01-23 16:33 UTC, SirSpidey commented on solutions/ibm-catalog/sap-s4hana-bw4hana/README.md
> +4. If you have a **Maintenance Planner Stack XML** file, place it under the **same folder as S4HANA_2022** and not under the HANA DB directory. Applies to all other versions as well. Mention only the
```suggestion
4. If you have a **maintenance planner stack XML** file, place it under the **same folder as S4HANA_2022** and not under the HANA DB directory. Applies to all other versions as well. Mention only the name of this file in **'cos_swpm_mp_stack_file_name'**. Leave it **empty** if you do not have this stack XML file.
```

2024-01-23 16:33 UTC, SirSpidey commented on solutions/sap-ready-to-go/README.md
> +- Post-instance provisioning, Ansible Galaxy collection roles from [IBM](https://galaxy.ansible.com/ui/repo/published/ibm/power_linux_sap/) are executed: `power_linux_sap`.
same comment as previous: correct?

2024-01-23 16:33 UTC, SirSpidey commented on solutions/sap-ready-to-go/README.md
> +## Before You Begin
```suggestion
## Before you begin
```

2024-01-23 16:33 UTC, SirSpidey commented on tests/README.md
> +For information about how to create and run tests, see [Validation Tests](https://terraform-ibm-modules.github.io/documentation/#/tests) in the project documentation.
```suggestion
For information about how to create and run tests, see [Validation tests](https://terraform-ibm-modules.github.io/documentation/#/tests) in the project documentation.
```

2024-01-24 08:58 UTC, surajsbharadwaj approved these changes

2024-01-24 08:58 UTC, surajsbharadwaj commented
/run pipeline

2024-01-24 11:49 UTC, surajsbharadwaj approved these changes

2024-01-24 15:55 UTC, merged

2024-01-29 17:55 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.6.1 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-powervs-sap/releases/tag/v1.6.1)
- `v1.6.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: