feat: 282 tok04 per
terraform-ibm-modules/terraform-ibm-powervs-sap pull request #626
Opened 2024-03-18 17:57 UTC by stafaniasaju

### Description

- Enabled PER for DC location tok04
- Added validation for prefix

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-03-18 17:57 UTC, stafaniasaju commented
/run pipeline

2024-03-18 21:50 UTC, surajsbharadwaj requested changes
Change IBM provider version to 1.63.0 for all DA solutions

2024-03-20 09:36 UTC, surajsbharadwaj requested changes
Also e2e must be updated to use 1.1.0 version

2024-03-20 09:36 UTC, surajsbharadwaj commented on modules/pi-sap-system-type1/main.tf
> +  pi_boot_image_storage_tier = "tier3"
This should be tier 1

2024-03-20 10:42 UTC, stafaniasaju commented
> Also e2e must be updated to use 1.1.0 version

e2e source refers to module which is already updated.
source     = "../../modules/pi-sap-system-type1" 

If this is not the intended part, can you point me to the line?

https://github.com/terraform-ibm-modules/terraform-ibm-powervs-sap/blob/a67954758b3711cced1e0aa7981c125378c734b9/modules/pi-sap-system-type1/main.tf#L48

2024-03-20 12:01 UTC, surajsbharadwaj commented on modules/pi-sap-system-type1/main.tf
> +  pi_boot_image_storage_tier = "tier3"
This has to be fixed @stafaniasaju

2024-03-20 19:32 UTC, surajsbharadwaj commented
/run pipeline

2024-03-26 11:27 UTC, closed without merging