feat: upgrade power_linux_sap roles
terraform-ibm-modules/terraform-ibm-powervs-sap pull request #741
Opened 2024-12-02 13:30 UTC by ludwig-mueller

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-12-02 15:22 UTC, surajsbharadwaj requested changes

2024-12-02 15:22 UTC, surajsbharadwaj commented on modules/ansible/templates-ansible/configure-os-for-sap/playbook-configure-os-for-sap.yml.tftpl
> +   - { role: ibm.power_linux_sap.powervs_configure_os_for_sap, when: sap_solution is defined, ignore_errors: true }
ignore_errors: this should be removed. Playbook and terraform should fail if any of the tasks fail

2024-12-02 15:22 UTC, surajsbharadwaj commented on modules/ansible/templates-ansible/configure-network-services/playbook-configure-network-services.yml.tftpl
>      when: client_config.keys()|length > 0
add one more  condition. It should be or condition
server_config.keys()|length > 0

2024-12-02 15:58 UTC, surajsbharadwaj commented
@ludwig-mueller please update the toc-version, last modified and version to 2.2.0. Also do a commit with SKIP UGRADE TEST: landing zone version upgrade"

2024-12-02 16:29 UTC, surajsbharadwaj submitted a review, later dismissed

2024-12-02 17:16 UTC, surajsbharadwaj commented
/run pipeline

2024-12-02 18:14 UTC, surajsbharadwaj commented
@ludwig-mueller sync with @stafaniasaju and include powervs_os_registration role and set fls true for checks to be performed.
Also keep in mind how to support BYOL (username and password for custom os images)

2024-12-02 20:13 UTC, surajsbharadwaj requested changes
Lines from 21 to 43 must be removed as v3.0.0 does it already in the role ibm.power_linux_sap.powervs_configure_os_for_sap,

2024-12-02 20:13 UTC, surajsbharadwaj commented on modules/ansible/templates-ansible/configure-os-for-sap/playbook-configure-os-for-sap.yml.tftpl
>    - include_role:
Lines from 21 to 43 must be removed as v3.0.0 does it already in the role ibm.power_linux_sap.powervs_configure_os_for_sap,

2024-12-04 14:21 UTC, ludwig-mueller commented
- PR for powervs_os_registration on instance repo is open, will update this repo to new version once that's merged
- Integration of byol in this repo and in instance needs further discussion

2024-12-07 18:08 UTC, surajsbharadwaj approved these changes

2024-12-07 18:09 UTC, merged

2024-12-07 18:09 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 3.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-powervs-sap/releases/tag/v3.2.0)
- `v3.2.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: